# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: "Continuous Integration"

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Validate composer.json and composer.lock"
        run: php7.3 $(which composer) validate --strict

      - name: "Install locked dependencies with composer"
        run: php7.3 $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Run localheinz/composer-normalize"
        run: php7.3 $(which composer) normalize --dry-run

      - name: "Run friendsofphp/php-cs-fixer"
        run: php7.3 vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --using-cache=no --verbose

  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install locked dependencies with composer"
        if: matrix.dependencies == 'locked'
        run: php7.3 $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Run unit tests with phpunit/phpunit"
        run: php7.3 vendor/bin/phpunit --configuration=phpunit.xml
